[default]
  host = "127.0.0.1"
  port = 8080
  testing = false
  # Random seed for currency rate adapter
  random_seed = 1234

[testing]
  testing = true
  [testing.db]
    username = "pguser"
    password = "pgpass"
    host = "localhost"
    port = 5437
    dbname = "pgdb"

[development]
  [development.db]
    username = "pguser"
    password = "pgpass"
    host = "localhost"
    port = 5436
    dbname = "pgdb"
