"""init migration

Revision ID: 602fb28c5c21
Revises: 
Create Date: 2019-11-11 02:35:51.572408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602fb28c5c21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
